tls:
  min_version: "1.3"
  cert_file: "repository/resources/security/server.cert"
  key_file: "repository/resources/security/server.key"

database:
  identity:
    type: "sqlite"
    path: "repository/database/thunderdb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

  runtime:
    type: "sqlite"
    path: "repository/database/runtimedb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

  user:
    type: "sqlite"
    path: "repository/database/userdb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

crypto:
  encryption:
    key: "file://repository/resources/security/crypto.key"
  keys:
    - id: "default-key"
      cert_file: "repository/resources/security/signing.cert"
      key_file: "repository/resources/security/signing.key"

jwt:
  preferred_key_id: "default-key"

server:
  hostname: "0.0.0.0"
  port: 8090
  public_url: "https://<domain_name>:<port>"

gate_client:
  hostname: "<domain_name>"
  port: <port>
  scheme: "https"
  path: "/gate"

cors:
  allowed_origins:
    - "https://<domain_name>:<port>"

passkey:
  allowed_origins:
    - "https://<domain_name>:<port>"
